spring:
  datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa.hibernate.ddl-auto: create
  h2.console:
    enabled: true
    path: /h2-console
debug: true